### ISSUE TITLE
Bug: Plugin Installation Failing for SQLite Database Type 

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/AddressBook#6]
- v1.1
- Sqlite

Found in debug.log: 
```[2023-07-03 09:56:01] [critical] AddressBook: Unable to migrate schema for the plugin: AddressBook => SQLSTATE[HY000]: General error: 1 near "AUTO_INCREMENT": syntax error```

_Originally posted by @PopovIG in https://github.com/aljawaid/AddressBook/discussions/5#discussioncomment-6341493_

**Comment by aljawaid** [comment]
Hi @PopovIG can you make a manual edit to the schema file and test the change for me to see if it works?

**Comment by PopovIG** [comment]
I tried version 1.2 - the plugin was displayed and working in the project settings.
But there are a couple of new bugs:
1. When opening a task
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 ambiguous column name: contacts_id
2. When deleting a contact
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 foreign key mismatch - "address_book_contacts_task_has_contact" referencing "address_book_contacts_contact"

**Comment by aljawaid** [comment]
What do you mean when opening a task? After you assigned contacts to it?

**Comment by PopovIG** [comment]
No, just after clicking on the task on the board

![image](https://github.com/aljawaid/AddressBook/assets/13576441/ce8bd167-e267-4376-b84b-1cde25218b9e)

**Comment by PopovIG** [comment]
_When deleting a contact
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 foreign key mismatch - "address_book_contacts_task_has_contact" referencing "address_book_contacts_contact"_

I changed "contacts_id INTEGER KEY NOT NULL" to "contacts_id INTEGER PRIMARY KEY NOT NULL" in Sqlite.php, it fixed this problem
